BEGIN;

-- System table for designated bank branches (e.g. National Bank of Pakistan)
-- Used for challan receiving and verification scoped by officer jurisdiction
CREATE TABLE IF NOT EXISTS public.designated_bank_branches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  serial_no integer NOT NULL,
  bank_name text NOT NULL DEFAULT 'National Bank of Pakistan',
  region text NOT NULL,
  district text NOT NULL,
  branch_name text NOT NULL,
  branch_code text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bank_branches_district ON public.designated_bank_branches(lower(district));
CREATE INDEX IF NOT EXISTS idx_bank_branches_code ON public.designated_bank_branches(branch_code);
CREATE INDEX IF NOT EXISTS idx_bank_branches_bank ON public.designated_bank_branches(lower(bank_name));

-- Function to query designated branches, optionally scoped by officer district
CREATE OR REPLACE FUNCTION public.get_designated_bank_branches(p_district text DEFAULT NULL)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', b.id,
        'serial_no', b.serial_no,
        'bank_name', b.bank_name,
        'region', b.region,
        'district', b.district,
        'branch_name', b.branch_name,
        'branch_code', b.branch_code,
        'is_active', b.is_active
      )
      ORDER BY b.district, b.branch_name
    ),
    '[]'::jsonb
  )
  FROM public.designated_bank_branches b
  WHERE b.is_active = true
    AND (
      p_district IS NULL
      OR trim(p_district) = ''
      OR lower(b.district) = lower(trim(p_district))
      OR lower(b.district) LIKE '%' || lower(trim(p_district)) || '%'
      OR lower(trim(p_district)) LIKE '%' || lower(b.district) || '%'
    );
$$;

REVOKE ALL ON FUNCTION public.get_designated_bank_branches(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_designated_bank_branches(text) TO authenticated, anon;

-- Seed branches from official designated NBP schedule
INSERT INTO public.designated_bank_branches (serial_no, bank_name, region, district, branch_name, branch_code)
VALUES
  (1, 'National Bank of Pakistan', 'D G Khan', 'D G Khan', 'Main Branch D G Khan', '326'),
  (2, 'National Bank of Pakistan', 'D G Khan', 'D G Khan', 'Taunsa Sharif', '473'),
  (3, 'National Bank of Pakistan', 'D G Khan', 'D G Khan', 'PAEC-BC', '1635'),
  (4, 'National Bank of Pakistan', 'D G Khan', 'D G Khan', 'Mouza Gadai', '863'),
  (5, 'National Bank of Pakistan', 'D G Khan', 'Layyah', 'Layyah Branch', '358'),
  (6, 'National Bank of Pakistan', 'D G Khan', 'Layyah', 'Karor Lal Eason', '1688'),
  (7, 'National Bank of Pakistan', 'D G Khan', 'Layyah', 'Chowk Azam', '1894'),
  (8, 'National Bank of Pakistan', 'D G Khan', 'Layyah', 'Choubara', '1687'),
  (9, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'M B MUZAFFAR GARH', '378'),
  (10, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'ALI PUR BRANCH', '446'),
  (11, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'JATOI BRANCH', '1969'),
  (12, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'KOT ADDU', '355'),
  (13, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'Chak 571/TDA', '1762'),
  (14, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'Khan Garh', '1900'),
  (15, 'National Bank of Pakistan', 'D G Khan', 'Muzaffargarh', 'Qasba Gujrat', '939'),
  (16, 'National Bank of Pakistan', 'D G Khan', 'Rajan Pur', 'RAJAN PUR', '392'),
  (17, 'National Bank of Pakistan', 'D G Khan', 'Rajan Pur', 'JAM PUR BRANCH', '439'),
  (18, 'National Bank of Pakistan', 'D G Khan', 'Rajan Pur', 'ROJHAN BRANCH', '1686'),
  (19, 'National Bank of Pakistan', 'D G Khan', 'Rajan Pur', 'Fazil Pur', '622'),
  (20, 'National Bank of Pakistan', 'D G Khan', 'Rajan Pur', 'Kot Mithan', '624'),
  (21, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Main Br.Rawalakot', '393'),
  (22, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Hajira Br.', '586'),
  (23, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Abbaspur Br.', '818'),
  (24, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Thorar Br.', '1425'),
  (25, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Khigala Br.', '1426'),
  (26, 'National Bank of Pakistan', 'Rawalakot AK', 'Poonch AK', 'Jandala Br.', '1673'),
  (27, 'National Bank of Pakistan', 'Rawalakot AK', 'Bagh AK', 'Main Br.Bagh', '447'),
  (28, 'National Bank of Pakistan', 'Rawalakot AK', 'Bagh AK', 'Chirala Branch', '1593'),
  (29, 'National Bank of Pakistan', 'Rawalakot AK', 'Bagh AK', 'Rangla Br.', '1659'),
  (30, 'National Bank of Pakistan', 'Rawalakot AK', 'Haveli AK', 'Kahutta Br.', '961'),
  (31, 'National Bank of Pakistan', 'Rawalakot AK', 'Haveli AK', 'Gogdar Br.', '1805'),
  (32, 'National Bank of Pakistan', 'Rawalakot AK', 'Sudhnoti AK', 'Pullandn Branch', '508'),
  (33, 'National Bank of Pakistan', 'Rawalakot AK', 'Sudhnoti AK', 'Trarkhel Br.', '819'),
  (34, 'National Bank of Pakistan', 'Rawalakot AK', 'Sudhnoti AK', 'Awanabad Br.', '1782'),
  (35, 'National Bank of Pakistan', 'Rawalakot AK', 'Sudhnoti AK', 'Ball Khan Mong Br.', '1835'),
  (36, 'National Bank of Pakistan', 'Sahiwal', 'Bahawal Nagar', 'Main Branch Bahawal Nagar', '307'),
  (37, 'National Bank of Pakistan', 'Sahiwal', 'Bahawal Nagar', 'Grain Market Fort Abbas', '329'),
  (38, 'National Bank of Pakistan', 'Sahiwal', 'Bahawal Nagar', 'Minchin Abad', '370'),
  (39, 'National Bank of Pakistan', 'Sahiwal', 'Bahawal Nagar', 'Bank Street Bahawal Nagar', '709'),
  (40, 'National Bank of Pakistan', 'Sahiwal', 'Bahawal Nagar', 'Chest Branch Haroon Abad', '715'),
  (41, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'Main Branch Okara', '383'),
  (42, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'Renala Khurd', '477'),
  (43, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'Depalpur', '498'),
  (44, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'Kuthehry Bazar Okara', '763'),
  (45, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'SQA Okra Cantt', '1627'),
  (46, 'National Bank of Pakistan', 'Sahiwal', 'Okara', 'Hujra Shah Muqeem', '458'),
  (47, 'National Bank of Pakistan', 'Sahiwal', 'Pakpattan', 'Thana Bazar Arifwala', '304'),
  (48, 'National Bank of Pakistan', 'Sahiwal', 'Pakpattan', 'College Road Pakpattan', '384'),
  (49, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'Grain Market Chichawatni', '317'),
  (50, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'District Courts Sahiwal', '373'),
  (51, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'City Branch Sahiwal', '536'),
  (52, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'Fareed Town Branch Sahiwal', '648'),
  (53, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'Jamia Masjid Chichawatni', '760'),
  (54, 'National Bank of Pakistan', 'Sahiwal', 'Sahiwal', 'Grain Market Sahiwal', '1514'),
  (55, 'National Bank of Pakistan', 'Gilgit', 'Gilgit', 'Main Branch Gilgit', '425'),
  (56, 'National Bank of Pakistan', 'Gilgit', 'Gilgit', 'Jutial Cantt Branch', '1434'),
  (57, 'National Bank of Pakistan', 'Gilgit', 'Gilgit', 'Danyore Branch', '2311'),
  (58, 'National Bank of Pakistan', 'Gilgit', 'Skardu', 'Skardu Branch', '486'),
  (59, 'National Bank of Pakistan', 'Gilgit', 'Skardu', 'Alamdar Chowk Branch', '2173'),
  (60, 'National Bank of Pakistan', 'Gilgit', 'Diamir', 'Chilas Branch', '504'),
  (61, 'National Bank of Pakistan', 'Gilgit', 'Ghizer', 'Gahkuch Branch', '2029'),
  (62, 'National Bank of Pakistan', 'Gilgit', 'Ghizer', 'Gupis Branch', '8886'),
  (63, 'National Bank of Pakistan', 'Gilgit', 'Astore', 'Astore Branch', '8885'),
  (64, 'National Bank of Pakistan', 'Gilgit', 'Hunza', 'Aliabad Branch', '2226'),
  (65, 'National Bank of Pakistan', 'Gilgit', 'Hunza', 'Karimabad Branch', '873'),
  (66, 'National Bank of Pakistan', 'Gilgit', 'Nagar', 'Sikandarabad Branch', '2227'),
  (67, 'National Bank of Pakistan', 'Gilgit', 'Ghanche', 'Khaplu Branch', '888'),
  (68, 'National Bank of Pakistan', 'Gilgit', 'Shigar', 'Shigar Branch', '2175'),
  (69, 'National Bank of Pakistan', 'Gilgit', 'Kharmong', 'Mehdiabad Branch', '874'),
  (70, 'National Bank of Pakistan', 'Muzaffarabad', 'Muzaffarabad', 'Main Branch Muzaffarabad', '377'),
  (71, 'National Bank of Pakistan', 'Muzaffarabad', 'AK', 'Civil Secretariat Branch', '660'),
  (72, 'National Bank of Pakistan', 'Muzaffarabad', 'AK', 'Upper Adda Branch', '1617'),
  (73, 'National Bank of Pakistan', 'Muzaffarabad', 'AK', 'Chattar Domel Branch', '1464'),
  (74, 'National Bank of Pakistan', 'Muzaffarabad', 'AK', 'Gojra Bypass Branch', '2248'),
  (75, 'National Bank of Pakistan', 'Muzaffarabad', 'AK', 'Pattika Branch', '1672'),
  (76, 'National Bank of Pakistan', 'Muzaffarabad', 'Hattian', 'Hattian Branch', '673'),
  (77, 'National Bank of Pakistan', 'Muzaffarabad', 'Hattian', 'Chikar Branch', '948'),
  (78, 'National Bank of Pakistan', 'Muzaffarabad', 'Bagh', 'Dhirkot Branch', '887'),
  (79, 'National Bank of Pakistan', 'Muzaffarabad', 'Neelum', 'Athmuqam Branch', '2092'),
  (80, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Main Branch, Gujrat', '335'),
  (81, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Main Branch Lalamusa.', '589'),
  (82, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Deona Mandi Branch.', '645'),
  (83, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Kunjah Branch.', '666'),
  (84, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Dinga Branch.', '787'),
  (85, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Railway Road Branch Gujrat.', '788'),
  (86, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Noonawali Branch', '792'),
  (87, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Jalalpur Jattan Branch.', '795'),
  (88, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Dullanwala Branch', '1727'),
  (89, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Kotla Arab Ali Khan.', '1975'),
  (90, 'National Bank of Pakistan', 'Gujrat', 'Gujrat', 'Bhimber Road Branch, Gujrat', '2312'),
  (91, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Main Branch Mandi Bahauddin.', '362'),
  (92, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Phalia Branch', '460'),
  (93, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Malakwal Branch.', '615'),
  (94, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Qadirabad Branch.', '790'),
  (95, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Mona Depot Branch', '870'),
  (96, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Mangat Branch.', '871'),
  (97, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Hardorerkabla Branch', '908'),
  (98, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Mano Chak Branch.', '1386'),
  (99, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Gojra Branch', '2196'),
  (100, 'National Bank of Pakistan', 'Gujrat', 'Mandi Bahauddin.', 'Kutchehry Road  Branch', '789'),
  (101, 'National Bank of Pakistan', 'Karachi', 'South', 'Main Branch', '2'),
  (102, 'National Bank of Pakistan', 'Karachi', 'South', 'DHA Branch', '9'),
  (103, 'National Bank of Pakistan', 'Karachi', 'South', 'Denso Hall Branch', '10'),
  (104, 'National Bank of Pakistan', 'Karachi', 'South', 'Nicol Road Branch', '44'),
  (105, 'National Bank of Pakistan', 'Karachi', 'South', 'PIDC House Branch', '50'),
  (106, 'National Bank of Pakistan', 'Karachi', 'South', 'Saddar Branch', '55'),
  (107, 'National Bank of Pakistan', 'Karachi', 'South', 'Income Tax Branch', '85'),
  (108, 'National Bank of Pakistan', 'Karachi', 'South', 'Hasrat Mohani Road Branch', '158'),
  (109, 'National Bank of Pakistan', 'Karachi', 'South', 'Nadir House Branch', '222'),
  (110, 'National Bank of Pakistan', 'Karachi', 'South', 'Haroon House Branch', '223'),
  (111, 'National Bank of Pakistan', 'Karachi', 'South', 'PNSC Building Branch', '250'),
  (112, 'National Bank of Pakistan', 'Karachi', 'South', 'Avari Tower Branch', '271'),
  (113, 'National Bank of Pakistan', 'Karachi', 'South', 'Model Clifton Branch', '1027'),
  (114, 'National Bank of Pakistan', 'Karachi', 'South', 'New Sindh Secretariat Branch', '1053'),
  (115, 'National Bank of Pakistan', 'Karachi', 'South', 'Massan Road Branch', '1065'),
  (116, 'National Bank of Pakistan', 'Karachi', 'South', 'Clifton Block 2 Branch', '2055'),
  (117, 'National Bank of Pakistan', 'Karachi', 'South', 'Kayaban E Ittehad Branch', '2100'),
  (118, 'National Bank of Pakistan', 'Karachi', 'South', 'Tauheed Commercial Branch', '2158'),
  (119, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Main Branch Bhalwal', '312'),
  (120, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Civil Lines Sargodha', '397'),
  (121, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Shahpur Saddar', '431'),
  (122, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Sillanwali', '532'),
  (123, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Bhagtanwala', '567'),
  (124, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Chak 46 SB', '579'),
  (125, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Sargodha City', '621'),
  (126, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Remount Depot Sargodha', '691'),
  (127, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Satellite Town Sargodha', '750'),
  (128, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Chak No.29 Sb', '1316'),
  (129, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Sial More', '1809'),
  (130, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Bhera', '1901'),
  (131, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Kotmomin', '1921'),
  (132, 'National Bank of Pakistan', 'Sargodha', 'Sargodha', 'Sahiwal', '1977'),
  (133, 'National Bank of Pakistan', 'Sargodha', 'Chiniot', 'SQA Chiniot', '319'),
  (134, 'National Bank of Pakistan', 'Sargodha', 'Chiniot', 'Chenab Nagar', '1308'),
  (135, 'National Bank of Pakistan', 'Sargodha', 'Chiniot', 'Thatha Musa', '1729'),
  (136, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Civil Lines', '360'),
  (137, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Main Branch Jaranwala', '342'),
  (138, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Main Branch Samundari', '423'),
  (139, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Abdullahpur', '559'),
  (140, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Dijkot Road', '1395'),
  (141, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Peoples Colony', '1478'),
  (142, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Uni. of Agriculture', '549'),
  (143, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Jinnah Colony', '1571'),
  (144, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Noorpur', '867'),
  (145, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Tandlianwala', '407'),
  (146, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Malikpur Manawala', '889'),
  (147, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Ayub Agriculture Research Institute', '560'),
  (148, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Chak Jhumra', '516'),
  (149, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Chak # 210/GB', '741'),
  (150, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Adda Dijkot', '1457'),
  (151, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Mamoon Kanjan', '1458'),
  (152, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Small Industrial Estate', '1955'),
  (153, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Chak # 229/RB', '1558'),
  (154, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Narwala Banglaw', '842'),
  (155, 'National Bank of Pakistan', 'Faisalabad', 'Faisalabad', 'Chak # 66/JB', '838'),
  (156, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Main Branch Larkana', '22'),
  (157, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Bank Square Branch', '211'),
  (158, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Ratodero Branch', '111'),
  (159, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Naudero Branch', '134'),
  (160, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Industrial Area Br.', '2325'),
  (161, 'National Bank of Pakistan', 'Larkana', 'Larkana', 'Dokri', '132'),
  (162, 'National Bank of Pakistan', 'Larkana', 'Kamber @ Shahdadkot', 'Kamber Ali Khan', '17'),
  (163, 'National Bank of Pakistan', 'Larkana', 'Kamber @ Shahdadkot', 'Shahdadkot Branch', '59'),
  (164, 'National Bank of Pakistan', 'Larkana', 'Kamber @ Shahdadkot', 'Nasirabad Branch', '129'),
  (165, 'National Bank of Pakistan', 'Larkana', 'Shikarpur', 'Main Branch Shikarpur', '61'),
  (166, 'National Bank of Pakistan', 'Larkana', 'Shikarpur', 'Hathidar Br: Shikarpur', '1927'),
  (167, 'National Bank of Pakistan', 'Larkana', 'Shikarpur', 'Garhi Yaseen Branch', '88'),
  (168, 'National Bank of Pakistan', 'Larkana', 'Kashmore @ Kandhkot', 'Kandhkot Branch', '74'),
  (169, 'National Bank of Pakistan', 'Larkana', 'Kashmore @ Kandhkot', 'Kashmore Branch', '115'),
  (170, 'National Bank of Pakistan', 'Larkana', 'Kashmore @ Kandhkot', 'Thull Branch', '106'),
  (171, 'National Bank of Pakistan', 'Larkana', 'Kashmore @ Kandhkot', 'Ghouspur Branch', '170'),
  (172, 'National Bank of Pakistan', 'Larkana', 'Jacobabad', 'TR Jacobabad Branch', '15'),
  (173, 'National Bank of Pakistan', 'Larkana', 'Dadu', 'Main Branch Dadu', '8'),
  (174, 'National Bank of Pakistan', 'Larkana', 'Dadu', 'K.N Shah Branch', '120'),
  (175, 'National Bank of Pakistan', 'Larkana', 'Dadu', 'Mehar Branch', '33'),
  (176, 'National Bank of Pakistan', 'Larkana', 'Dadu', 'Johi Branch', '102'),
  (177, 'National Bank of Pakistan', 'Swat', 'Swat', 'Main Branch Saidu Sharif', '1330'),
  (178, 'National Bank of Pakistan', 'Swat', 'Swat', 'Bank Square Mingora', '438'),
  (179, 'National Bank of Pakistan', 'Swat', 'Swat', 'Khwaza Khela', '1911'),
  (180, 'National Bank of Pakistan', 'Swat', 'Swat', 'Matta', '663'),
  (181, 'National Bank of Pakistan', 'Swat', 'Swat', 'Barikot', '1970'),
  (182, 'National Bank of Pakistan', 'Swat', 'Swat', 'Thana', '1842'),
  (183, 'National Bank of Pakistan', 'Swat', 'Swat', 'Kabal Bazar', '2009'),
  (184, 'National Bank of Pakistan', 'Swat', 'Shangla', 'Alpuri', '1934'),
  (185, 'National Bank of Pakistan', 'Swat', 'Lower DIR', 'Main Branch Timergara', '841'),
  (186, 'National Bank of Pakistan', 'Swat', 'Lower DIR', 'Chakdara', '1331'),
  (187, 'National Bank of Pakistan', 'Swat', 'Lower DIR', 'Main Branch Dir', '328'),
  (188, 'National Bank of Pakistan', 'Swat', 'Lower DIR', 'Warai', '1323'),
  (189, 'National Bank of Pakistan', 'Swat', 'Bajawar', 'Khar Branch', '1595'),
  (190, 'National Bank of Pakistan', 'Swat', 'Chitral', 'Main Branch Chitral', '321'),
  (191, 'National Bank of Pakistan', 'Swat', 'Chitral', 'Booni Branch', '1866'),
  (192, 'National Bank of Pakistan', 'Swat', 'Chitral', 'Drosh Branch', '1581'),
  (193, 'National Bank of Pakistan', 'Multan', 'Khanewal', 'Main Branch, Kabirwala', '345'),
  (194, 'National Bank of Pakistan', 'Multan', 'Khanewal', 'Abdul Hakim Branch', '417'),
  (195, 'National Bank of Pakistan', 'Multan', 'Khanewal', 'Kukkar Hatta Branch', '905'),
  (196, 'National Bank of Pakistan', 'Multan', 'Multan', 'Main Branch, Multan', '374'),
  (197, 'National Bank of Pakistan', 'Multan', 'Multan', 'City Branch Multan', '375'),
  (198, 'National Bank of Pakistan', 'Multan', 'Multan', 'Main Branch Shujabad', '402'),
  (199, 'National Bank of Pakistan', 'Multan', 'Multan', 'Cantt Branch, Multan', '437'),
  (200, 'National Bank of Pakistan', 'Multan', 'Multan', 'Gulgasht Colony, Multan', '542'),
  (201, 'National Bank of Pakistan', 'Multan', 'Multan', 'Jalalpur Pirwala Branch.', '544'),
  (202, 'National Bank of Pakistan', 'Multan', 'Multan', 'Qadirpur Rawan Branch', '585'),
  (203, 'National Bank of Pakistan', 'Multan', 'Multan', 'Lar Branch', '627'),
  (204, 'National Bank of Pakistan', 'Multan', 'Multan', 'Timber Market Multan.', '835'),
  (205, 'National Bank of Pakistan', 'Multan', 'Multan', 'Mumtazabad Br Multan', '1490'),
  (206, 'National Bank of Pakistan', 'Multan', 'Multan', 'Dera Adda Branch, Multan', '1495'),
  (207, 'National Bank of Pakistan', 'Multan', 'Multan', 'Haram Gate, Multan', '1527'),
  (208, 'National Bank of Pakistan', 'Multan', 'Multan', 'Bosan Road, Multan', '1931'),
  (209, 'National Bank of Pakistan', 'Multan', 'Multan', 'Shah Rukn-e-Alam, Multan', '1995'),
  (210, 'National Bank of Pakistan', 'Multan', 'Multan', 'Wapda Town Multan.', '2071'),
  (211, 'National Bank of Pakistan', 'Multan', 'Multan', 'Adda Band Bosan', '2315'),
  (212, 'National Bank of Pakistan', 'Mianwali', 'Bhakkar', 'Main Branch Bhakkar', '311'),
  (213, 'National Bank of Pakistan', 'Mianwali', 'Bhakkar', 'Draya Khan Branch', '1427'),
  (214, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Main Branch Mianwali', '369'),
  (215, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Liaqatabad Branch', '428'),
  (216, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Kalabagh Branch', '985'),
  (217, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Chashma Barrage', '502'),
  (218, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Daud Khel Branch', '1548'),
  (219, 'National Bank of Pakistan', 'Mianwali', 'Mianwali', 'Wan Bhachran Branch', '2243'),
  (220, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Main Branch Joharabad', '436'),
  (221, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Khushab Branch', '353'),
  (222, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Naushera Branch', '1662'),
  (223, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Noorpur Thal Branch', '1685'),
  (224, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Katha Sagral Branch', '924'),
  (225, 'National Bank of Pakistan', 'Mianwali', 'Khushab', 'Pail Branch', '679'),
  (226, 'National Bank of Pakistan', 'Bannu', 'Bannu', 'Bannu City Branch', '309'),
  (227, 'National Bank of Pakistan', 'Bannu', 'Bannu', 'Jadid Abadi Bannu', '1401'),
  (228, 'National Bank of Pakistan', 'Bannu', 'Bannu', 'K.N.F. Khel Branch', '1415'),
  (229, 'National Bank of Pakistan', 'Bannu', 'Bannu', 'Bannu Cantt Branch', '552'),
  (230, 'National Bank of Pakistan', 'Bannu', 'Dera Ismail Khan', 'Main Branch D.I.Khan', '327'),
  (231, 'National Bank of Pakistan', 'Bannu', 'Dera Ismail Khan', 'Lar Branch D.I. Khan', '1327'),
  (232, 'National Bank of Pakistan', 'Bannu', 'Dera Ismail Khan', 'Gomal University', '1373'),
  (233, 'National Bank of Pakistan', 'Bannu', 'Dera Ismail Khan', 'Paroa Road  D.I. Khan', '1545'),
  (234, 'National Bank of Pakistan', 'Bannu', 'Dera Ismail Khan', 'Circular Road Branch DIK', '1433'),
  (235, 'National Bank of Pakistan', 'Bannu', 'Hango', 'Hangu Branch', '420'),
  (236, 'National Bank of Pakistan', 'Bannu', 'Hango', 'Tall Branch', '411'),
  (237, 'National Bank of Pakistan', 'Bannu', 'Karak', 'Karak Branch', '451'),
  (238, 'National Bank of Pakistan', 'Bannu', 'Karak', 'Faqirabad Branch', '1743'),
  (239, 'National Bank of Pakistan', 'Bannu', 'Karak', 'Takht-e-Nusrati Branch', '1918'),
  (240, 'National Bank of Pakistan', 'Bannu', 'Lakki Marwat', 'Main Branch Lakki Marwat', '426'),
  (241, 'National Bank of Pakistan', 'Bannu', 'Lakki Marwat', 'Sarai Naurang', '964'),
  (242, 'National Bank of Pakistan', 'Bannu', 'Lakki Marwat', 'Serai Gambeela Branch', '1391'),
  (243, 'National Bank of Pakistan', 'Bannu', 'Miranshah', 'Miranshah Branch', '453'),
  (244, 'National Bank of Pakistan', 'Bannu', 'Parachinar', 'Parachinar Branch', '385'),
  (245, 'National Bank of Pakistan', 'Bannu', 'Tank', 'Tank City Branch', '408'),
  (246, 'National Bank of Pakistan', 'Bannu', 'Tank', 'Sadam Shoping Center Branch Tank', '1851'),
  (247, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Main Branch Abbottabad', '301'),
  (248, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Abbottabad City Branch', '591'),
  (249, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Khola Keyal Branch', '1876'),
  (250, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Mandian Mirpur Branch', '1348'),
  (251, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Havelian Branch', '424'),
  (252, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Nawansher Branch', '488'),
  (253, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Lora Branch', '1609'),
  (254, 'National Bank of Pakistan', 'Abbottabad', 'Abbottabad', 'Takia Hall Branch', '1822'),
  (255, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Main Branch Haripur', '337'),
  (256, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Shahrah-e-Hazara Branch', '827'),
  (257, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'TIP Branch Haripur', '505'),
  (258, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Sikandar pur Branch', '1979'),
  (259, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'NTTS Branch Haripur', '826'),
  (260, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Ghazi Branch', '499'),
  (261, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Khanpur Dam Branch', '582'),
  (262, 'National Bank of Pakistan', 'Abbottabad', 'Haripur', 'Sarai Saleh Branch', '952'),
  (263, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Civil Lines Branch Sheikhupura', '401'),
  (264, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Grain Market Sheikhupura', '781'),
  (265, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Farooqabad', '464'),
  (266, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Sharaqpur', '400'),
  (267, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Bhikhi', '1403'),
  (268, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Ahmedpur', '535'),
  (269, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Kot Abdul Malik', '1986'),
  (270, 'National Bank of Pakistan', 'Sheikhupura', 'Sheikhupura', 'Manawala', '1985'),
  (271, 'National Bank of Pakistan', 'Sheikhupura', 'Nankana Sahib', 'Sangla Hill', '581'),
  (272, 'National Bank of Pakistan', 'Sheikhupura', 'Nankana Sahib', 'Shahkot', '534'),
  (273, 'National Bank of Pakistan', 'Sheikhupura', 'Nankana Sahib', 'GM Nankana Sahib', '379'),
  (274, 'National Bank of Pakistan', 'Sheikhupura', 'Nankana Sahib', 'Warburton', '478'),
  (275, 'National Bank of Pakistan', 'Sheikhupura', 'Hafizabad', 'Sukheke Mandi', '776'),
  (276, 'National Bank of Pakistan', 'Sheikhupura', 'Hafizabad', 'Main Branch Hafizabad', '336'),
  (277, 'National Bank of Pakistan', 'Sheikhupura', 'Hafizabad', 'Pindi Bhttian', '1502'),
  (278, 'National Bank of Pakistan', 'Mardan', 'Attock', 'Main Br Attock', '315'),
  (279, 'National Bank of Pakistan', 'Mardan', 'Attock', 'Hazro Br', '1584'),
  (280, 'National Bank of Pakistan', 'Mardan', 'Attock', 'Pindi Gheb', '459'),
  (281, 'National Bank of Pakistan', 'Mardan', 'Attock', 'Jand', '1779'),
  (282, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Main Br Mardan', '365'),
  (283, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Takht Bhai Br', '548'),
  (284, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Katlang', '884'),
  (285, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Rustam', '1352'),
  (286, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'A.W.K Univ Mardan', '2233'),
  (287, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Mayar Branch', '828'),
  (288, 'National Bank of Pakistan', 'Mardan', 'Mardan', 'Nowshera Road Br.', '2242'),
  (289, 'National Bank of Pakistan', 'Mardan', 'Malakand', 'Dargai br', '620'),
  (290, 'National Bank of Pakistan', 'Mardan', 'Malakand', 'Main Br Malakand', '419'),
  (291, 'National Bank of Pakistan', 'Mardan', 'Malakand', 'U.C Mkd', '1990'),
  (292, 'National Bank of Pakistan', 'Mardan', 'Malakand', 'Sakhakot Br.', '593'),
  (293, 'National Bank of Pakistan', 'Mardan', 'Buner', 'Main Br Daggar', '1704'),
  (294, 'National Bank of Pakistan', 'Mardan', 'Swabi', 'Main Br Swabi', '406'),
  (295, 'National Bank of Pakistan', 'Mardan', 'Swabi', 'Turlandi Br Swabi', '1870'),
  (296, 'National Bank of Pakistan', 'Mardan', 'Swabi', 'Topi Branch', '503'),
  (297, 'National Bank of Pakistan', 'Mardan', 'Swabi', 'Kunda Branch', '1313'),
  (298, 'National Bank of Pakistan', 'Mardan', 'Swabi', 'Zaida Branch', '1972'),
  (299, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Civil Lines Gujranwala', '333'),
  (300, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'City Branch Gujranwala', '334'),
  (301, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Main Branch Wazirabad', '418'),
  (302, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'S.I.E.Gujranwala', '513'),
  (303, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Alipur Chatha', '541'),
  (304, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'G.T Road Ghakhar', '766'),
  (305, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Atta Building', '767'),
  (306, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Ghalla Mandi Kamoke', '770'),
  (307, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'More Eminabad', '772'),
  (308, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Nowshera Virkan', '773'),
  (309, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Qila Didar Singh', '774'),
  (310, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'G.T.Road Muridke', '779'),
  (311, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Gulabpura Cantt', '892'),
  (312, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Satellite Town', '1498'),
  (313, 'National Bank of Pakistan', 'Gujranwala', 'Gujranwala', 'Model Town', '1610'),
  (314, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Main Br Islamabad', '341'),
  (315, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Main Br Murree', '376'),
  (316, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Aabpara', '1456'),
  (317, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Capt.Naeem Tufail', '2067'),
  (318, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'G-9 Markaz', '1932'),
  (319, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'F-10 Markaz', '1933'),
  (320, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'F-8 Markaz', '1694'),
  (321, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Industrial Area', '1531'),
  (322, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'S-Block', '485'),
  (323, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'D-Block', '501'),
  (324, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'B-Block', '880'),
  (325, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Margalla', '1725'),
  (326, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Foreign Office', '474'),
  (327, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'P.M Secct', '1732'),
  (328, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'PARC', '1539'),
  (329, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'A.I.O.U', '977'),
  (330, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'N.H Q', '1469'),
  (331, 'National Bank of Pakistan', 'Islamabad', 'Islmabad', 'Ghora Gali', '692'),
  (332, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'Fatima jinnah', '14'),
  (333, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'MARKET AREA', '30'),
  (334, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'LATIFABAD 08', '91'),
  (335, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'QASIMABAD', '2031'),
  (336, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'NEW CLOTH', '43'),
  (337, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'TANDO JAM', '177'),
  (338, 'National Bank of Pakistan', 'Hyderabad', 'Hyderabad', 'WAPDA COLONY', '1057'),
  (339, 'National Bank of Pakistan', 'Hyderabad', 'Badin', 'BADIN', '4'),
  (340, 'National Bank of Pakistan', 'Hyderabad', 'Badin', 'MATLI', '96'),
  (341, 'National Bank of Pakistan', 'Hyderabad', 'Badin', 'GOLARCHI', '1044'),
  (342, 'National Bank of Pakistan', 'Hyderabad', 'Badin', 'TALHAR', '2022'),
  (343, 'National Bank of Pakistan', 'Hyderabad', 'Badin', 'TANDO Bago', '75'),
  (344, 'National Bank of Pakistan', 'Hyderabad', 'Thatta', 'Thatta', '70'),
  (345, 'National Bank of Pakistan', 'Hyderabad', 'Thatta', 'MAKLI', '81'),
  (346, 'National Bank of Pakistan', 'Hyderabad', 'Thatta', 'MIR Pur SAKRO', '92'),
  (347, 'National Bank of Pakistan', 'Hyderabad', 'Matiari', 'MATYARI', '2020'),
  (348, 'National Bank of Pakistan', 'Hyderabad', 'Matiari', 'HALA', '2251'),
  (349, 'National Bank of Pakistan', 'Hyderabad', 'Tando Allah Yar', 'TANDO ALLAHYAR', '68'),
  (350, 'National Bank of Pakistan', 'Hyderabad', 'Tando Muhammad Khan', 'TANDO MUHAMMAD KHAN', '69'),
  (351, 'National Bank of Pakistan', 'Hyderabad', 'Sujawal', 'SUJAWAL', '76'),
  (352, 'National Bank of Pakistan', 'Hyderabad', 'Sujawal', 'MIR PUR BATHARO', '35'),
  (353, 'National Bank of Pakistan', 'Hyderabad', 'Jamshoro', 'SITE NOORIBAD', '1720'),
  (354, 'National Bank of Pakistan', 'Hyderabad', 'Jamshoro', 'KOTRI', '21'),
  (355, 'National Bank of Pakistan', 'Hyderabad', 'Jamshoro', 'SANN', '2303'),
  (356, 'National Bank of Pakistan', 'Hyderabad', 'Jamshoro', 'SINDH UNIVERSITY', '226'),
  (357, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Main Branch Rawalpindi', '394'),
  (358, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'RAWALPINDI CITY.', '395'),
  (359, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'SATELLIT TOWN BRANCH', '399'),
  (360, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Wah Cantt', '415'),
  (361, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'KAHUTA BRANCH', '442'),
  (362, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Fateh Jang', '454'),
  (363, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Hassanabdal', '467'),
  (364, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Kallar Syedan', '521'),
  (365, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'PAF CHAKLALA BRANCH', '557'),
  (366, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'EME COLLEGE RAWALPINDI', '640'),
  (367, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'RWP CANTT.BOARD BUILDING.', '642'),
  (368, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'KHANNA DAK DISTT R''PINDI', '963'),
  (369, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'HPTC Rawat Branch', '1506'),
  (370, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'HEAVY REBUILT FAC TAXILLA CANT', '1542'),
  (371, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'SHALIMAR PLAZA RAWALPINDI', '1623'),
  (372, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Passport Office', '1666'),
  (373, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'SUMBALGAH DISTT R.PINDI', '1683'),
  (374, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'P.A.C KAMRA, ATTOCK', '1351'),
  (375, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'ATTOCK OIL COMPANY MORGAH', '639'),
  (376, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'Noor Khan Air Base', '2202'),
  (377, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'PESHAWAR ROAD RAWALPINDI', '1508'),
  (378, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'DISTRICT COUNCIL RAWALPINDI', '638'),
  (379, 'National Bank of Pakistan', 'Rawalpindi', 'Rawalpindi', 'ADIYALA ROAD BRANCH', '2321'),
  (380, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Main Branch Jhang', '343'),
  (381, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Shorkot City', '471'),
  (382, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Jhang City Branch', '636'),
  (383, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Chund Branch', '675'),
  (384, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Community Centre Br Jhang', '752'),
  (385, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Garhmore Branch', '1754'),
  (386, 'National Bank of Pakistan', 'Jhang', 'Jhang', 'Ahmed Pur Sial', '1974'),
  (387, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'Main Branch Gojra', '331'),
  (388, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'Kamalia City', '347'),
  (389, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'City Br Toba Tek Singh', '412'),
  (390, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'Main Branch Pirmahal', '533'),
  (391, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'Grain Market Br Gojra', '742'),
  (392, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'K.B. Kamalia', '1734'),
  (393, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'D.C. Br Toba Tek Singh', '1924'),
  (394, 'National Bank of Pakistan', 'Jhang', 'Toba Tek Singh', 'Nia Lahore Branch', '2234'),
  (395, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'Kutchery Road Branch Ahmadpur East', '302'),
  (396, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'District Court Bahawalpur', '308'),
  (397, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'Yazman Branch', '606'),
  (398, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'Farid Gate Branch', '701'),
  (399, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'Uch Sharif Branch', '703'),
  (400, 'National Bank of Pakistan', 'Bahawalpur', 'Bahawalpur', 'Satlitetown Branch Bahawalpur', '957'),
  (401, 'National Bank of Pakistan', 'Bahawalpur', 'Lohdran', 'Lohdran Branch', '470'),
  (402, 'National Bank of Pakistan', 'Bahawalpur', 'Lohdran', 'Kehror Pacca Brach', '623'),
  (403, 'National Bank of Pakistan', 'Bahawalpur', 'Lohdran', 'Denote', '732'),
  (404, 'National Bank of Pakistan', 'Bahawalpur', 'Lohdran', 'Dunyapur Branch', '836'),
  (405, 'National Bank of Pakistan', 'Bahawalpur', 'Lohdran', 'City Branch Lohdran', '2179'),
  (406, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Chest Branch Khanpur', '350'),
  (407, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Liaqatpur Branch', '359'),
  (408, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Model Town Branch Rahimyarkhan', '391'),
  (409, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Chest Branch Sadiqabad', '396'),
  (410, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'ZahirPir Branch', '731'),
  (411, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Feroza Branch', '1437'),
  (412, 'National Bank of Pakistan', 'Bahawalpur', 'Rahim Yar Khan', 'Pull Sunny Branch', '1568'),
  (413, 'National Bank of Pakistan', 'Jhelum', 'Rawalpindi', 'G.T. Road Gujar Khan', '332'),
  (414, 'National Bank of Pakistan', 'Jhelum', 'Rawalpindi', 'Daultala', '803'),
  (415, 'National Bank of Pakistan', 'Jhelum', 'Rawalpindi', 'Gulyana', '643'),
  (416, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Civil Lines Jhelum', '344'),
  (417, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Pind Dadan Khan', '432'),
  (418, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Mangla Road Dina', '616'),
  (419, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'G.T. Road Sohawa', '1812'),
  (420, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Domeli', '1460'),
  (421, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Chak Khasa', '1383'),
  (422, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Muhammadi Bazar', '1583'),
  (423, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Khewra', '352'),
  (424, 'National Bank of Pakistan', 'Jhelum', 'Jhelum', 'Mangal Cantt.', '363'),
  (425, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Main Branch Chakwal', '421'),
  (426, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Talagang', '422'),
  (427, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Choa Saiden Shah', '556'),
  (428, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Dhudial', '1615'),
  (429, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Chakora Kallar Kahar', '1885'),
  (430, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Lawa', '2099'),
  (431, 'National Bank of Pakistan', 'Jhelum', 'Chakwal', 'Bangwala', '1884'),
  (432, 'National Bank of Pakistan', 'Jhelum', 'Gujrat', 'Kharian City', '512'),
  (433, 'National Bank of Pakistan', 'Jhelum', 'Gujrat', 'Sarai Alamgir', '569'),
  (434, 'National Bank of Pakistan', 'Mirpurkhas', 'Mirpurkhas', 'Digri', '11'),
  (435, 'National Bank of Pakistan', 'Mirpurkhas', 'Mirpurkhas', 'Kot Ghulam Muhammad', '16'),
  (436, 'National Bank of Pakistan', 'Mirpurkhas', 'Mirpurkhas', 'Main Branch Mirpurkhas', '36'),
  (437, 'National Bank of Pakistan', 'Mirpurkhas', 'Mirpurkhas', 'Municipal Corporation Mirp', '39'),
  (438, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Main Branch Nawabshah', '40'),
  (439, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Sakrand Branch', '56'),
  (440, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Engg. University Nawabshah', '293'),
  (441, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Kazi Ahmed Branch', '169'),
  (442, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Mohni Bazar Nawabshah', '230'),
  (443, 'National Bank of Pakistan', 'Mirpurkhas', 'Nawabshah', 'Dour', '1033'),
  (444, 'National Bank of Pakistan', 'Mirpurkhas', 'Sanghar', 'Main Branch Sanghar', '57'),
  (445, 'National Bank of Pakistan', 'Mirpurkhas', 'Sanghar', 'Shahdadpur Branch', '58'),
  (446, 'National Bank of Pakistan', 'Mirpurkhas', 'Sanghar', 'Tando Adam', '67'),
  (447, 'National Bank of Pakistan', 'Mirpurkhas', 'Sanghar', 'Khipro', '98'),
  (448, 'National Bank of Pakistan', 'Mirpurkhas', 'Umerkot', 'Samaro', '83'),
  (449, 'National Bank of Pakistan', 'Mirpurkhas', 'Umerkot', 'Umerkot Branch', '110'),
  (450, 'National Bank of Pakistan', 'Mirpurkhas', 'Umerkot', 'Kunri', '2030'),
  (451, 'National Bank of Pakistan', 'Mirpurkhas', 'Mithi', 'Mithi', '116'),
  (452, 'National Bank of Pakistan', 'Mirpurkhas', 'Mithi', 'Islamkot', '195'),
  (453, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Manan chowk Branch', '1860'),
  (454, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Quetta City', '51'),
  (455, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Quetta Cantt', '52'),
  (456, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Satellite Town', '1083'),
  (457, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'B.M.C. Branch Quetta', '184'),
  (458, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Almo Chowk Br Quetta', '2188'),
  (459, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Nawan killi Branch', '2259'),
  (460, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Alamdar Road Branch', '2106'),
  (461, 'National Bank of Pakistan', 'Quetta', 'Quetta', 'Ind Esate Branch', '297'),
  (462, 'National Bank of Pakistan', 'Quetta', 'Pishin', 'Pishin', '136'),
  (463, 'National Bank of Pakistan', 'Quetta', 'Kila Abdullah', 'Chaman', '5'),
  (464, 'National Bank of Pakistan', 'Quetta', 'Killa Siaf ullah', 'Killa Siafullah', '1061'),
  (465, 'National Bank of Pakistan', 'Quetta', 'Killa Siaf ullah', 'Muslim Bagh', '151'),
  (466, 'National Bank of Pakistan', 'Quetta', 'Zhob', 'Zhob', '101'),
  (467, 'National Bank of Pakistan', 'Quetta', 'Nushki', 'Nushki', '175'),
  (468, 'National Bank of Pakistan', 'Quetta', 'Chagi', 'Dalbandin', '174'),
  (469, 'National Bank of Pakistan', 'Quetta', 'Kharan', 'Kharan', '154'),
  (470, 'National Bank of Pakistan', 'Quetta', 'Washuk', 'Washuk', '2066'),
  (471, 'National Bank of Pakistan', 'Quetta', 'Ziarat', 'Ziarat', '210'),
  (472, 'National Bank of Pakistan', 'Sibi', 'Sibi', 'Sibi', '119'),
  (473, 'National Bank of Pakistan', 'Sibi', 'Bolan', 'Dhadar', '176'),
  (474, 'National Bank of Pakistan', 'Sibi', 'Bolan', 'Bhagh', '1989'),
  (475, 'National Bank of Pakistan', 'Sibi', 'Lehri', 'Lehri', '206'),
  (476, 'National Bank of Pakistan', 'Sibi', 'Naseerabad', 'Dera Murad Jamali', '1072'),
  (477, 'National Bank of Pakistan', 'Sibi', 'Jaffarabad', 'Dera Allah yar', '105'),
  (478, 'National Bank of Pakistan', 'Sibi', 'Jaffarabad', 'Usta  Muhammad', '1962'),
  (479, 'National Bank of Pakistan', 'Sibi', 'Sohbat pur', 'Sohbat pur', '2247'),
  (480, 'National Bank of Pakistan', 'Sibi', 'Dera Bugti', 'Dera Bugti', '1045'),
  (481, 'National Bank of Pakistan', 'Sibi', 'Dera Bugti', 'Sui', '2193'),
  (482, 'National Bank of Pakistan', 'Sibi', 'Kohlu', 'Kohlu', '209'),
  (483, 'National Bank of Pakistan', 'Sibi', 'Barkhan', 'Barkhan', '204'),
  (484, 'National Bank of Pakistan', 'Sibi', 'Musa Khel', 'Musa Khel', '1040'),
  (485, 'National Bank of Pakistan', 'Sibi', 'Loralai', 'Loralai', '26'),
  (486, 'National Bank of Pakistan', 'Sibi', 'Duki', 'Duki', '1050'),
  (487, 'National Bank of Pakistan', 'Sibi', 'Harnai', 'Harnai', '155'),
  (488, 'National Bank of Pakistan', 'Lahore East', 'Kasur', 'Main Branch Kasur', '348'),
  (489, 'National Bank of Pakistan', 'Lahore East', 'Kasur', 'Chunian Branch', '322'),
  (490, 'National Bank of Pakistan', 'Lahore East', 'Kasur', 'Kot Radha Kishan Branch', '515'),
  (491, 'National Bank of Pakistan', 'Lahore East', 'Kasur', 'Pattoki Branch', '462'),
  (492, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Raiwind Branch', '518'),
  (493, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Ismail Nagar Branch', '1587'),
  (494, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Shahpur Kanjran Branch', '1655'),
  (495, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Township Branch', '1669'),
  (496, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Model Town Branch', '372'),
  (497, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'LDA Plaza Branch', '466'),
  (498, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'ACP Model Branch', '1442'),
  (499, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Model Branch Gulberg', '1569'),
  (500, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Jail Road Branch', '509'),
  (501, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Punjab University Branch', '2045'),
  (502, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Sh. Zayed Hospital Branch', '1707'),
  (503, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Bahria Town Branch', '2215'),
  (504, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Moon Market Branch', '1887'),
  (505, 'National Bank of Pakistan', 'Lahore East', 'Lahore', 'Wahdat Road Branch', '979'),
  (506, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'MB Daska', '325'),
  (507, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'District Courts', '403'),
  (508, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Cantt', '404'),
  (509, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'City', '405'),
  (510, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'MB Pasrur', '434'),
  (511, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Sambrial', '481'),
  (512, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Chawinda', '562'),
  (513, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'S.I.E.', '608'),
  (514, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Jandoke Goraya', '670'),
  (515, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Dulchike', '946'),
  (516, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Randhir More', '1319'),
  (517, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Bullowal Kalan', '1360'),
  (518, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'TM Pasrur', '1546'),
  (519, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Gohadpur', '1626'),
  (520, 'National Bank of Pakistan', 'Sialkot', 'Sialkot', 'Kingra', '1678'),
  (521, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'MB Narowal', '381'),
  (522, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'RR Shakargarh', '435'),
  (523, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'Baddomalhi', '482'),
  (524, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'Kanjrur', '682'),
  (525, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'Maingri', '683'),
  (526, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'Jaman Chandowal', '1730'),
  (527, 'National Bank of Pakistan', 'Sialkot', 'Narowal', 'Zafarwal', '2077'),
  (528, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'Main BRANCH Mirpur, AK', '371'),
  (529, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'CHAKSWARI, AK', '445'),
  (530, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'DISTT.COURTS BR. MIRPUR AK', '472'),
  (531, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'SEC. C-4 BR. MIRPUR, AK', '604'),
  (532, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'IND. AREA MIRPUR, AK', '975'),
  (533, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'KAKRA TOWN, AK', '1306'),
  (534, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'Main Branch Dadyal AK', '444'),
  (535, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'JATLAN BRANCH, AK', '1466'),
  (536, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'KHADIMABAD,AK', '844'),
  (537, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'AKALGARH, AK', '1463'),
  (538, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'WAPDA COLONY MANGLA, AK', '614'),
  (539, 'National Bank of Pakistan', 'Mirpur AK', 'Mirpur AK', 'K. B. DADYAL, AK', '1846'),
  (540, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'M. B. KOTLI, AK', '441'),
  (541, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'BRAND BHATTA, AK', '816'),
  (542, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'GULPUR, AK', '817'),
  (543, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'SEHNSA BRANCH, AK', '1302'),
  (544, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'NIKYAL BRANCH, AK', '1303'),
  (545, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'CHAROHI, AK', '1462'),
  (546, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'KHUIRATTA BRANCH AK', '1465'),
  (547, 'National Bank of Pakistan', 'Mirpur AK', 'Kotli AK', 'Leri Tatapani Branch AK', '1788'),
  (548, 'National Bank of Pakistan', 'Mirpur AK', 'Bhimber AK', 'Bhimber Branch AK', '455'),
  (549, 'National Bank of Pakistan', 'Mirpur AK', 'Bhimber AK', 'SAMAHNI, AK', '1787'),
  (550, 'National Bank of Pakistan', 'Mirpur AK', 'Bhimber AK', 'Barnal Branch AK', '1845'),
  (551, 'National Bank of Pakistan', 'Mirpur AK', 'Bhimber AK', 'Dist Complex Branch Bhimber AK', '2217'),
  (552, 'National Bank of Pakistan', 'Karachi West', 'Central', 'NAZIMABAD', '42'),
  (553, 'National Bank of Pakistan', 'Karachi West', 'Central', 'NORTH KARACHI', '1086'),
  (554, 'National Bank of Pakistan', 'Karachi West', 'Central', 'SAKHI HASSAN', '1067'),
  (555, 'National Bank of Pakistan', 'Karachi West', 'Central', 'Orangi Town', '1055'),
  (556, 'National Bank of Pakistan', 'Karachi West', 'East', 'AWAMI MARKAZ', '1920'),
  (557, 'National Bank of Pakistan', 'Karachi West', 'East', 'DISTRICT COUNCIL', '108'),
  (558, 'National Bank of Pakistan', 'Karachi West', 'East', 'F.T.C.', '274'),
  (559, 'National Bank of Pakistan', 'Karachi West', 'East', 'P.E.C.H.S.(CBA)', '48'),
  (560, 'National Bank of Pakistan', 'Karachi West', 'East', 'SHAHEED-E-MILLAT RD', '144'),
  (561, 'National Bank of Pakistan', 'Karachi West', 'Kemari', 'PNAD MAURIPUR', '180'),
  (562, 'National Bank of Pakistan', 'Karachi West', 'Kemari', 'S.I.T.E.', '64'),
  (563, 'National Bank of Pakistan', 'Karachi West', 'Korangi', 'KORANGI INDUS. AREA', '255'),
  (564, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'AIRPORT', '3'),
  (565, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'C.O.D.', '159'),
  (566, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'LANDHI TOWNSHIP', '257'),
  (567, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'MODEL COLONY', '1070'),
  (568, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'N.E.D. UNIVERSITY', '1063'),
  (569, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'PORT QASIM', '279'),
  (570, 'National Bank of Pakistan', 'Karachi West', 'Malir', 'S.P.I.T. LANDHI', '103'),
  (571, 'National Bank of Pakistan', 'Karachi West', 'South', 'M.A. JINNAH ROAD', '27'),
  (572, 'National Bank of Pakistan', 'Karachi West', 'West', 'KANNUP Br', '152'),
  (573, 'National Bank of Pakistan', 'Gwadar', 'Gwadar', 'Gwadar', '79'),
  (574, 'National Bank of Pakistan', 'Gwadar', 'Gwadar', 'Deep Sea Port Br', '2258'),
  (575, 'National Bank of Pakistan', 'Gwadar', 'Lasbela', 'Hub Chowki', '258'),
  (576, 'National Bank of Pakistan', 'Gwadar', 'Lasbela', 'Uthal', '109'),
  (577, 'National Bank of Pakistan', 'Gwadar', 'Lasbela', 'Main Bazar Hub', '2191'),
  (578, 'National Bank of Pakistan', 'Gwadar', 'Lasbela', 'Windar', '1089'),
  (579, 'National Bank of Pakistan', 'Gwadar', 'Lasbela', 'Bela', '145'),
  (580, 'National Bank of Pakistan', 'Gwadar', 'Khuzdar', 'Khuzdar', '192'),
  (581, 'National Bank of Pakistan', 'Gwadar', 'Kalat', 'Kalat', '1049'),
  (582, 'National Bank of Pakistan', 'Gwadar', 'Mastung', 'Mastung', '31'),
  (583, 'National Bank of Pakistan', 'Gwadar', 'Turbat', 'Turbat', '140'),
  (584, 'National Bank of Pakistan', 'Gwadar', 'Turbat', 'Main Bazar Turbat', '2186'),
  (585, 'National Bank of Pakistan', 'Gwadar', 'Surab', 'Surab', '1994'),
  (586, 'National Bank of Pakistan', 'Gwadar', 'Awaran', 'Awaran', '1993'),
  (587, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Main Branch, Lahore', '300'),
  (588, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Lahore Cantt Branch', '356'),
  (589, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Regal Chowk Branch', '409'),
  (590, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Rehman Plaza Branch', '1857'),
  (591, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'DHS T Block Branch', '323'),
  (592, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Bagbanpura Branch', '540'),
  (593, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Wapda House Branch', '416'),
  (594, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Shahdra Branch', '452'),
  (595, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Durand Road Branch', '483'),
  (596, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Chaubrji Branch', '493'),
  (597, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Dina Nath Branch', '877'),
  (598, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Anarkali Branch', '303'),
  (599, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Badami Bagh Branch', '1997'),
  (600, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Saddar Bazar', '1523'),
  (601, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Mughalpura Branch', '649'),
  (602, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Walton Road', '1618'),
  (603, 'National Bank of Pakistan', 'Lahore Central', 'Lahore', 'Davis Road Branch', '1524'),
  (604, 'National Bank of Pakistan', 'Peshawar', 'Charsadda', 'Tehsil BazarCharsada', '410'),
  (605, 'National Bank of Pakistan', 'Peshawar', 'Charsadda', 'Shabqadar', '1435'),
  (606, 'National Bank of Pakistan', 'Peshawar', 'Kohat', 'Main Branch Kohat', '354'),
  (607, 'National Bank of Pakistan', 'Peshawar', 'Kohat', 'Behzadi Chakar Kot', '918'),
  (608, 'National Bank of Pakistan', 'Peshawar', 'Kohat', 'Hangu Road Kohat', '1311'),
  (609, 'National Bank of Pakistan', 'Peshawar', 'Kohat', 'Lachi', '1452'),
  (610, 'National Bank of Pakistan', 'Peshawar', 'Kohat', 'K.D.A.Kohat', '1803'),
  (611, 'National Bank of Pakistan', 'Peshawar', 'Nowshera', 'Saddar Bazar Nowshera', '566'),
  (612, 'National Bank of Pakistan', 'Peshawar', 'Nowshera', 'Taru Jabba', '824'),
  (613, 'National Bank of Pakistan', 'Peshawar', 'Nowshera', 'Shaidu', '1431'),
  (614, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Nowshera Cantt', '382'),
  (615, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Peshawar Cantt', '386'),
  (616, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Peshawar City', '387'),
  (617, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'University Campus', '388'),
  (618, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'G.T.Road', '517'),
  (619, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Khyber Bazar', '598'),
  (620, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Civil Secretariat', '986'),
  (621, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Warsak Road', '1499'),
  (622, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Kohat Road', '1512'),
  (623, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Hayatabad Township', '1759'),
  (624, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Saddar Road Peshawar', '1859'),
  (625, 'National Bank of Pakistan', 'Peshawar', 'Peshawar', 'Ring Road', '2300'),
  (626, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'M Br Mansehra', '364'),
  (627, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Balakot Branch', '574'),
  (628, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Oghi Branch', '617'),
  (629, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Gari Habibullah Branch', '665'),
  (630, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Lassan Nawab Sahib', '1358'),
  (631, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Village Dab Mansehra', '1372'),
  (632, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Baffa', '1423'),
  (633, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Hazara University', '1487'),
  (634, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'College Chowk Mansehra', '1798'),
  (635, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Village Noghazi Mansehra', '1907'),
  (636, 'National Bank of Pakistan', 'Mansehra', 'Mansehra', 'Shinkyari Cantt', '1797'),
  (637, 'National Bank of Pakistan', 'Mansehra', 'Shangla Swat', 'Bisham Branch', '1535'),
  (638, 'National Bank of Pakistan', 'Mansehra', 'Upper Kohistan', 'Dassu', '1691'),
  (639, 'National Bank of Pakistan', 'Mansehra', 'Battagram', 'Battagram', '926'),
  (640, 'National Bank of Pakistan', 'Mansehra', 'Abbottabad', 'Dhani', '1376'),
  (641, 'National Bank of Pakistan', 'Mansehra', 'Torghar', 'Judbah', '2087'),
  (642, 'National Bank of Pakistan', 'Mansehra', 'Lower Kohistan', 'Pattan', '1377'),
  (643, 'National Bank of Pakistan', 'Vehari', 'VEHARI', 'Main Branch, Burewala', '314'),
  (644, 'National Bank of Pakistan', 'Vehari', 'VEHARI', 'Main Branch, Vehari', '414'),
  (645, 'National Bank of Pakistan', 'Vehari', 'VEHARI', 'Main Branch, Mailsi', '497'),
  (646, 'National Bank of Pakistan', 'Vehari', 'VEHARI', 'Ghalla Mandi Burewala', '738'),
  (647, 'National Bank of Pakistan', 'Vehari', 'VEHARI', 'Ghalla Mandi Gaggoo', '761'),
  (648, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'Main Branch, Mianchannu', '368'),
  (649, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'Jahanian Branch', '550'),
  (650, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'CHAK NO 168/10 R', '1801'),
  (651, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'D.C. Branch, Khanewal', '734'),
  (652, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'T.C. Branch, Mianchannu', '1839'),
  (653, 'National Bank of Pakistan', 'Vehari', 'Khanewal', 'Katcha Khuh Branch', '561'),
  (654, 'National Bank of Pakistan', 'Vehari', 'Bahawalpur', 'Ghalla Mandi HasilPur', '339'),
  (655, 'National Bank of Pakistan', 'Vehari', 'Bahawalpur', 'Khair Pur Tamewali', '705'),
  (656, 'National Bank of Pakistan', 'Vehari', 'Bahawal Nagar', 'Main Road Chishtian', '320'),
  (657, 'National Bank of Pakistan', 'Vehari', 'Bahawal Nagar', 'Ghalla Mandi Chishtian', '710'),
  (658, 'National Bank of Pakistan', 'Vehari', 'Bahawal Nagar', 'Dharanwala', '712'),
  (659, 'National Bank of Pakistan', 'Sukkur', 'Ghotki', 'Ghotki Branch', '118'),
  (660, 'National Bank of Pakistan', 'Sukkur', 'Ghotki', 'Mirpur Mathelo Branch', '137'),
  (661, 'National Bank of Pakistan', 'Sukkur', 'Ghotki', 'Ubauro Branch', '213'),
  (662, 'National Bank of Pakistan', 'Sukkur', 'Ghotki', 'Daharki Branch', '1928'),
  (663, 'National Bank of Pakistan', 'Sukkur', 'Ghotki', 'Khanpur Mahar Branch', '2103'),
  (664, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Main Branch Khairpur', '19'),
  (665, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Kotdiji Branch', '135'),
  (666, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Thari Mirwah Branch', '212'),
  (667, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Pir Jo Goth', '95'),
  (668, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Ranipur Branch', '214'),
  (669, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Gambat Branch', '13'),
  (670, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Setharja Branch', '141'),
  (671, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Pacca Chang Branch', '190'),
  (672, 'National Bank of Pakistan', 'Sukkur', 'Khairpur Mirs', 'Chundiko Branch', '241'),
  (673, 'National Bank of Pakistan', 'Sukkur', 'Naushahro Feroze', 'Naushahro Feroze Branch', '41'),
  (674, 'National Bank of Pakistan', 'Sukkur', 'Naushahro Feroze', 'Kandiaro Branch', '93'),
  (675, 'National Bank of Pakistan', 'Sukkur', 'Naushahro Feroze', 'Mehrabpur Branch', '34'),
  (676, 'National Bank of Pakistan', 'Sukkur', 'Naushahro Feroze', 'Paddidon Branch', '2023'),
  (677, 'National Bank of Pakistan', 'Sukkur', 'Sukkur', 'Main Branch Sukkur', '65'),
  (678, 'National Bank of Pakistan', 'Sukkur', 'Sukkur', 'Pano Akil City Branch', '46'),
  (679, 'National Bank of Pakistan', 'Sukkur', 'Sukkur', 'Rohri Branch', '54'),
  (680, 'National Bank of Pakistan', 'Sukkur', 'Sukkur', 'Saleh Pat Branch', '2101')
ON CONFLICT DO NOTHING;

COMMIT;
